# Generated by Django 2.1.1 on 2018-09-07 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['name'], 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ['level'], 'verbose_name_plural': 'Rows'},
        ),
        migrations.AlterField(
            model_name='row',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='application.Entry'),
        ),
        migrations.AlterField(
            model_name='row',
            name='level',
            field=models.CharField(max_length=200),
        ),
    ]
